### ISSUE TITLE
[Hexo 使用问题汇报] Next 主题评论数显示错误

### ISSUE THREAD

**Issue by jcglqmoyx** [EasyHexo/Easy-Hexo#89]
- 问题简介（*）
文章末尾评论数统计
- Hexo 版本（*）
6.X

- 使用的主题以及版本（*）
NexT
- 预想结果（*）
每篇文章末尾有用户留言评论时，文章预览处的评论数应该增加1.
- 实际结果（*）
无论留言多少，评论数显示都为0
- 您的网站
https://jcglqmoyx.github.io/
- 其他信息

**Comment by jcglqmoyx** [comment]
谢谢大佬指点^_^

**Comment by ChungZH** [comment]
初步判断是 Hexo 配置文件问题，请把 Hexo 根目录的 `_config.yml` 贴出来一下，谢谢！

**Comment by jcglqmoyx** [comment]
您好，这是我的_config.yml文件

Sent from Mail for Windows 10

**Comment by ChungZH** [comment]
（看不到啊）

**Comment by ChungZH** [comment]
@jcglqmoyx 可以重发一遍吗？

**Comment by jcglqmoyx** [comment]
`# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
menu:
  home: https://jcglqmoyx.github.io/
  About:
  Articles:
  archives:

# Site
title: Chintsai
subtitle: It's never too old to learn.
description: It's never too old to learn.
keywords: Chintsai
author: Chintsai
language: en
timezone: 

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
plugins: hexo-generate-feed

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  repo: git@github.com:jcglqmoyx/jcglqmoyx.github.io.git
  branch: master`

**Comment by ChungZH** [comment]
把 `url: http://yoursite.com` 改成 `url: https://jcglqmoyx.github.io/` 试一下。

**Comment by jcglqmoyx** [comment]
`# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
menu:
  home: https://jcglqmoyx.github.io/
  About:
  Articles:
  archives:

# Site
title: Chintsai
subtitle: It's never too old to learn.
description: It's never too old to learn.
keywords: Chintsai
author: Chintsai
language: en
timezone: 

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
plugins: hexo-generate-feed

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  repo: git@github.com:jcglqmoyx/jcglqmoyx.github.io.git
  branch: master`

**Comment by jcglqmoyx** [comment]
`

`

**Comment by ChungZH** [comment]
？？？

**Comment by ChungZH** [comment]
怎么样了

**Comment by jcglqmoyx** [comment]
不会上传多行代码。。。

**Comment by ChungZH** [comment]
@jcglqmoyx https://segmentfault.com/a/1190000017476570#articleHeader9

**Comment by jcglqmoyx** [comment]
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
menu:
  home: https://jcglqmoyx.github.io/
  About:
  Articles:
  archives:

# Site
title: Chintsai
subtitle: It's never too old to learn.
description: It's never too old to learn.
keywords: Chintsai
author: Chintsai
language: en
timezone: 

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://jcglqmoyx.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
plugins: hexo-generate-feed

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  repo: git@github.com:jcglqmoyx/jcglqmoyx.github.io.git
  branch: master
```
